### ISSUE TITLE
[Wishlist][ Feature Request] - Add Additional Document types to Schema

### ISSUE THREAD

**Issue by StoltHD** [alephdata/visdesktop#4]
There are no "Document" Node entity in Vis Desktop, I need to register both Patents and Patent Applications in addition to other types of documents, i.e. letters or Personal Notes, Newspaper Articles and Company Advertisements, I know this is a little out of the scope, but if it was possible for you to add a "Document" Node Entity with a Field of "Type", I can add Custom Types for each Document myself.

My project is more of historical than "Investigating Journalism", but your software is easy to use and with some small adjustments it can be used for a wide range of research...

Great job, I 'm about to install and configure Aleph also, having a few thousand sources and documents.

**Comment by StoltHD** [comment]
I still can't don't have a "Document" type or any way to add custom "types" in vis-desktop...
It looks like there are only a little subset of entities types hard coded in the software...

![bilde](https://user-images.githubusercontent.com/28066567/68752210-33af0c80-0603-11ea-8975-54faedcd44c2.png)

![bilde](https://user-images.githubusercontent.com/28066567/68752257-4aedfa00-0603-11ea-8d7c-1d2bf96d6c56.png)

you state that the software support the same entities as "follow the money", but in this list there is only a small portion of it...?

**Comment by pudo** [comment]
We've disabled `Document` and all it's descencants in VIS for the moment. These entity types are created when people upload data to Aleph, but it requires a lot of background functionality for interpreting the contents of a particular document (e.g. pulling contents out of a Word Document, or E-Mail).

At the moment, my preference would be not to let users create these types directly with stub contents, since that would make Aleph and VIS incompatible in weird and hard-to-predict ways (e.g. there would suddenly be documents with no file size, or underlying data blob).

Of course, you always have the option of building your own edition of VIS Desktop with a modified version of the domain model ("Follow the Money") built into it. You'd need to set `generated` to false everywhere and then fix all the resulting unexpected behaviour:

https://github.com/alephdata/followthemoney/blob/master/followthemoney/schema/Document.yaml#L6

**Comment by pudo** [comment]
To clarify a bit further: we hope to have a second "edition" of VIS run inside Aleph fairly soon, which is why keeping the two things compatible is an essential objective for us.

**Comment by StoltHD** [comment]
Okay, I just don't see the difference between a "document" and a Contract or a Tax Roll, or a Customs Declaration... Here in Norway all of those "types" er also documents... same with Passport...

But I can wait and see how the aleph functionality will work out, I was going to test out a local install of Aleph, so then I will just wait untill the version with VIS are ready... Hopefully you will find it possible to eneble it in the desktop then... :-)

thanks for explaining...

I liked the desktop version

I'm no developer so trying to create my own version are not an alternative for me... sadly... but tanks for the tip...
